import test, { after, before } from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';

const port = 31987;
const base = `http://127.0.0.1:${port}`;
let child;
async function waitForServer(){const deadline=Date.now()+5000;while(Date.now()<deadline){try{const response=await fetch(`${base}/api/health`);if(response.ok)return;}catch{}await new Promise(r=>setTimeout(r,50));}throw new Error('server did not become ready');}
before(async()=>{child=spawn(process.execPath,['server.js'],{cwd:process.cwd(),env:{...process.env,PORT:String(port),DATABASE_URL:''},stdio:['ignore','pipe','pipe']});await waitForServer();});
after(()=>child?.kill('SIGTERM'));
async function register(email,organizationName){const response=await fetch(`${base}/api/auth/register`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password:'Test-password-123!',organizationName})});assert.equal(response.status,201);return response.headers.get('set-cookie').split(';')[0];}
function authHeaders(cookie){return{cookie,'content-type':'application/json'};}

test('health endpoint reports v0.6.0',async()=>{const response=await fetch(`${base}/api/health`);assert.equal(response.status,200);const body=await response.json();assert.equal(body.ok,true);assert.equal(body.version,'0.6.0');});
test('v1 endpoints require a valid authenticated session',async()=>{const response=await fetch(`${base}/api/v1/clients`);assert.equal(response.status,401);assert.deepEqual(await response.json(),{error:'unauthorized'});});
test('register creates a session and /me returns current organization',async()=>{const cookie=await register('owner@example.test','Owner Studio');const response=await fetch(`${base}/api/auth/me`,{headers:{cookie}});assert.equal(response.status,200);const data=(await response.json()).data;assert.equal(data.user.email,'owner@example.test');assert.equal(data.organization.name,'Owner Studio');assert.equal(data.role,'owner');});
test('login rejects wrong password and accepts correct password',async()=>{await register('login@example.test','Login Studio');const bad=await fetch(`${base}/api/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:'login@example.test',password:'wrong-password'})});assert.equal(bad.status,401);const good=await fetch(`${base}/api/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:'login@example.test',password:'Test-password-123!'})});assert.equal(good.status,200);assert.match(good.headers.get('set-cookie'),/pilot_session=/);});
test('organization settings persist for the authenticated owner',async()=>{const cookie=await register('settings@example.test','Settings Studio');const patch=await fetch(`${base}/api/v1/organization`,{method:'PATCH',headers:authHeaders(cookie),body:JSON.stringify({name:'Settings Studio SRL',email:'billing@settings.example',address:'Rue du Test 10, 1000 Bruxelles',vatNumber:'BE0123.456.789',iban:'BE68 5390 0754 7034'})});assert.equal(patch.status,200);const saved=(await patch.json()).data;assert.equal(saved.vatNumber,'BE0123.456.789');const get=await fetch(`${base}/api/v1/organization`,{headers:{cookie}});const read=(await get.json()).data;assert.equal(read.iban,'BE68 5390 0754 7034');assert.equal(read.name,'Settings Studio SRL');});
test('clients invoices and documents are isolated by authenticated organization',async()=>{const alpha=await register('alpha@example.test','Alpha');const beta=await register('beta@example.test','Beta');await fetch(`${base}/api/v1/organization`,{method:'PATCH',headers:authHeaders(alpha),body:JSON.stringify({name:'Alpha SRL',email:'billing@alpha.example',address:'Rue Alpha 1, 1000 Bruxelles',vatNumber:'BE0999.999.999',iban:'BE68 5390 0754 7034'})});const created=await fetch(`${base}/api/v1/clients`,{method:'POST',headers:authHeaders(alpha),body:JSON.stringify({name:'Alpha Client',email:'hello@alpha.example',address:'Rue Client 2',vatNumber:'BE0111.111.111'})});assert.equal(created.status,201);const client=(await created.json()).data;const own=await fetch(`${base}/api/v1/clients`,{headers:{cookie:alpha}});assert.equal((await own.json()).data.length,1);const other=await fetch(`${base}/api/v1/clients`,{headers:{cookie:beta}});assert.equal((await other.json()).data.length,0);const invoiceResponse=await fetch(`${base}/api/v1/invoices`,{method:'POST',headers:authHeaders(alpha),body:JSON.stringify({clientId:client.id,client:client.name,lines:[{description:'Conseil',quantity:2,unitPrice:100,vat:21,discount:0}]})});assert.equal(invoiceResponse.status,201);const invoice=(await invoiceResponse.json()).data;assert.equal(invoice.totals.gross,242);const document=await fetch(`${base}/api/v1/invoices/${invoice.id}/document`,{headers:{cookie:alpha}});assert.equal(document.status,200);assert.match(document.headers.get('content-type'),/text\/html/);const html=await document.text();assert.match(html,/FACTURE/);assert.match(html,/Alpha SRL/);assert.match(html,/Alpha Client/);assert.match(html,/242/);const forbiddenDoc=await fetch(`${base}/api/v1/invoices/${invoice.id}/document`,{headers:{cookie:beta}});assert.equal(forbiddenDoc.status,404);const crossTenant=await fetch(`${base}/api/v1/invoices`,{method:'POST',headers:authHeaders(beta),body:JSON.stringify({clientId:client.id,client:client.name,lines:[{description:'Bad',quantity:1,unitPrice:1,vat:21}]})});assert.equal(crossTenant.status,400);assert.deepEqual(await crossTenant.json(),{error:'invalid_client'});});
test('quote lifecycle converts exactly once into an invoice',async()=>{const cookie=await register('quote@example.test','Quote Studio');const clientResponse=await fetch(`${base}/api/v1/clients`,{method:'POST',headers:authHeaders(cookie),body:JSON.stringify({name:'Quote Client',email:'quote-client@example.test'})});const client=(await clientResponse.json()).data;const created=await fetch(`${base}/api/v1/quotes`,{method:'POST',headers:authHeaders(cookie),body:JSON.stringify({clientId:client.id,validUntil:'2026-09-30',lines:[{description:'Site vitrine',quantity:1,unitPrice:1000,vat:21,discount:0}]})});assert.equal(created.status,201);const quote=(await created.json()).data;assert.match(quote.number,/^DEV-\d{4}-0001$/);assert.equal(quote.totals.gross,1210);const sent=await fetch(`${base}/api/v1/quotes/${quote.id}/status`,{method:'PATCH',headers:authHeaders(cookie),body:JSON.stringify({status:'sent'})});assert.equal((await sent.json()).data.status,'sent');const accepted=await fetch(`${base}/api/v1/quotes/${quote.id}/status`,{method:'PATCH',headers:authHeaders(cookie),body:JSON.stringify({status:'accepted'})});assert.equal((await accepted.json()).data.status,'accepted');const converted=await fetch(`${base}/api/v1/quotes/${quote.id}/convert`,{method:'POST',headers:authHeaders(cookie),body:'{}'});assert.equal(converted.status,201);const data=(await converted.json()).data;assert.equal(data.quote.status,'converted');assert.equal(data.invoice.sourceQuoteId,quote.id);assert.equal(data.invoice.totals.gross,1210);const second=await fetch(`${base}/api/v1/quotes/${quote.id}/convert`,{method:'POST',headers:authHeaders(cookie),body:'{}'});assert.equal(second.status,409);assert.equal((await second.json()).error,'quote_already_converted');const invoices=(await (await fetch(`${base}/api/v1/invoices`,{headers:{cookie}})).json()).data;assert.equal(invoices.filter(i=>i.sourceQuoteId===quote.id).length,1);});
test('quote from one organization cannot be read or converted by another',async()=>{const a=await register('qa@example.test','QA');const b=await register('qb@example.test','QB');const client=(await (await fetch(`${base}/api/v1/clients`,{method:'POST',headers:authHeaders(a),body:JSON.stringify({name:'QA Client'})})).json()).data;const quote=(await (await fetch(`${base}/api/v1/quotes`,{method:'POST',headers:authHeaders(a),body:JSON.stringify({clientId:client.id,lines:[{description:'Audit',quantity:1,unitPrice:200,vat:21,discount:0}]})})).json()).data;assert.equal((await fetch(`${base}/api/v1/quotes/${quote.id}`,{headers:{cookie:b}})).status,404);assert.equal((await fetch(`${base}/api/v1/quotes/${quote.id}/convert`,{method:'POST',headers:authHeaders(b),body:'{}'})).status,404);});
test('logout invalidates the session',async()=>{const cookie=await register('logout@example.test','Logout Studio');const logout=await fetch(`${base}/api/auth/logout`,{method:'POST',headers:{cookie,'content-type':'application/json'},body:'{}'});assert.equal(logout.status,204);const me=await fetch(`${base}/api/auth/me`,{headers:{cookie}});assert.equal(me.status,401);});
