const seedClients=[{id:'local-1',name:'Atelier Vermeulen',email:'contact@atelier.example'},{id:'local-2',name:'Studio Louise',email:'hello@studio.example'},{id:'local-3',name:'Nova Services',email:'admin@nova.example'}];
const seedInvoices=[{key:'local-18',id:'FAC-2026-018',client:'Atelier Vermeulen',clientId:'local-1',date:'08/08/2026',amount:1452,status:'Payée'},{key:'local-17',id:'FAC-2026-017',client:'Studio Louise',clientId:'local-2',date:'04/08/2026',amount:968,status:'En attente'},{key:'local-16',id:'FAC-2026-016',client:'Nova Services',clientId:'local-3',date:'29/07/2026',amount:660,status:'En retard'},{key:'local-15',id:'FAC-2026-015',client:'Atelier Vermeulen',clientId:'local-1',date:'22/07/2026',amount:2178,status:'Payée'}];
const load=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}};
let clients=load('pilot_clients',seedClients),invoices=load('pilot_invoices',seedInvoices),apiMode=false,currentUser=null;
const euro=n=>new Intl.NumberFormat('fr-BE',{style:'currency',currency:'EUR'}).format(Number(n)||0);
const statusClass=s=>s==='Payée'?'paid':s==='En retard'?'late':'pending';
const toast=msg=>{const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),2200)};
const api=async(path,options={})=>{const response=await fetch(path,{...options,credentials:'same-origin',headers:{...(options.body?{'content-type':'application/json'}:{}),...(options.headers||{})}});const body=response.status===204?null:await response.json().catch(()=>null);if(!response.ok){const error=new Error(body?.error||`HTTP_${response.status}`);error.status=response.status;error.body=body;throw error}return body};
function mapApiStatus(status){return status==='paid'?'Payée':status==='overdue'?'En retard':'En attente'}
function mapUiStatus(status){return status==='Payée'?'paid':status==='En retard'?'overdue':'issued'}
function normalizeApiInvoice(row){const client=clients.find(c=>c.id===row.clientId);return {key:row.id,id:row.number,client:client?.name||'Client',clientId:row.clientId,date:new Date(row.issueDate).toLocaleDateString('fr-BE'),amount:row.totals?.gross||0,status:mapApiStatus(row.status)}}
async function detectApi(){try{const response=await fetch('/api/health',{cache:'no-store'});if(!response.ok)return false;return (await response.json())?.service==='pilot'}catch{return false}}
async function hydrateFromApi(){const clientBody=await api('/api/v1/clients');clients=clientBody.data;const invoiceBody=await api('/api/v1/invoices');invoices=invoiceBody.data.map(normalizeApiInvoice)}
function persistLocal(){if(apiMode)return;localStorage.setItem('pilot_clients',JSON.stringify(clients));localStorage.setItem('pilot_invoices',JSON.stringify(invoices))}

document.querySelector('#today').textContent=new Intl.DateTimeFormat('fr-BE',{dateStyle:'long'}).format(new Date());
function row(i){return `<tr><td><b>${i.id}</b></td><td>${i.client}</td><td>${i.date}</td><td><b>${euro(i.amount)}</b></td><td><span class="status ${statusClass(i.status)}">${i.status}</span></td><td><button class="row-action" data-key="${i.key}">•••</button></td></tr>`}
function renderInvoices(filter=''){const visible=invoices.filter(i=>(i.id+' '+i.client).toLowerCase().includes(filter.toLowerCase()));document.querySelector('#invoiceRows').innerHTML=invoices.slice(0,5).map(row).join('');document.querySelector('#allInvoiceRows').innerHTML=visible.map(row).join('');const paid=invoices.filter(i=>i.status==='Payée'),pending=invoices.filter(i=>i.status==='En attente'),late=invoices.filter(i=>i.status==='En retard');const pendingTotal=pending.reduce((a,i)=>a+i.amount,0),lateTotal=late.reduce((a,i)=>a+i.amount,0);document.querySelector('#paidCount').textContent=paid.length;document.querySelector('#pendingCount').textContent=pending.length;document.querySelector('#lateCount').textContent=late.length;document.querySelector('#pendingAmount').textContent=euro(pendingTotal);document.querySelector('#lateAmount').textContent=euro(lateTotal);document.querySelector('#outstanding').textContent=euro(pendingTotal+lateTotal);document.querySelector('#revenue').textContent=euro(paid.reduce((a,i)=>a+i.amount,0)+(apiMode?0:9210));bindRowActions()}
function bindRowActions(){document.querySelectorAll('.row-action').forEach(btn=>btn.onclick=async()=>{const inv=invoices.find(i=>i.key===btn.dataset.key);if(!inv)return;const next=inv.status==='Payée'?'En attente':'Payée';if(!confirm(`${inv.id} — ${inv.client}\n\nPasser le statut à « ${next} » ?`))return;try{if(apiMode){const body=await api(`/api/v1/invoices/${inv.key}/status`,{method:'PATCH',body:JSON.stringify({status:mapUiStatus(next)})});inv.status=mapApiStatus(body.data.status)}else{inv.status=next;persistLocal()}renderInvoices(document.querySelector('#invoiceSearch')?.value||'');toast(`Statut mis à jour : ${inv.status}`)}catch{toast('Impossible de modifier le statut')}})}
function renderClients(){document.querySelector('#clientCards').innerHTML=clients.map(c=>`<div class="client-card"><b>${c.name}</b><span>${c.email||'E-mail non renseigné'}</span></div>`).join('');document.querySelector('#client').innerHTML=clients.map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}
function renderApp(){renderClients();renderInvoices();if(currentUser){document.querySelector('.aside-foot small').textContent=currentUser.organization?.name||'Espace entreprise';document.querySelector('.aside-foot b').textContent=currentUser.user.email}}

document.querySelectorAll('.nav').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.nav,.view').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelector('#'+btn.dataset.view).classList.add('active')}));
const dialog=document.querySelector('#invoiceDialog');document.querySelectorAll('#newInvoice,.invoice-trigger').forEach(b=>b.addEventListener('click',()=>dialog.showModal()));document.querySelector('#closeDialog').addEventListener('click',()=>dialog.close());
const amount=document.querySelector('#amount'),vat=document.querySelector('#vat');function preview(){const base=Number(amount.value)||0;document.querySelector('#totalPreview').textContent=euro(base*(1+Number(vat.value)/100))}amount.addEventListener('input',preview);vat.addEventListener('change',preview);
document.querySelector('#invoiceForm').addEventListener('submit',async e=>{e.preventDefault();const base=Number(amount.value);if(!Number.isFinite(base)||base<=0){toast('Montant invalide');return}const clientId=document.querySelector('#client').value;const client=clients.find(c=>c.id===clientId);const description=document.querySelector('#description').value.trim();try{if(apiMode){const body=await api('/api/v1/invoices',{method:'POST',body:JSON.stringify({clientId,client:client?.name||'Client',lines:[{description,quantity:1,unitPrice:base,vat:Number(vat.value),discount:0}]})});invoices.unshift(normalizeApiInvoice(body.data))}else{const total=Math.round(base*(1+Number(vat.value)/100)*100)/100;const max=invoices.reduce((m,i)=>Math.max(m,Number(i.id.split('-').pop())||0),0);invoices.unshift({key:`local-${Date.now()}`,id:`FAC-${new Date().getFullYear()}-${String(max+1).padStart(3,'0')}`,client:client?.name||'Client',clientId,date:new Date().toLocaleDateString('fr-BE'),amount:total,status:'En attente'});persistLocal()}renderInvoices();e.target.reset();preview();dialog.close();document.querySelector('[data-view="invoices"]').click();toast('Facture créée avec succès')}catch{toast('Impossible de créer la facture')}});
document.querySelector('#addClient').addEventListener('click',async()=>{const name=prompt('Nom du client');if(!name)return;const email=prompt('E-mail du client')||'';try{if(apiMode){const body=await api('/api/v1/clients',{method:'POST',body:JSON.stringify({name,email})});clients.push(body.data)}else{clients.push({id:`local-${Date.now()}`,name,email});persistLocal()}renderClients();toast('Client ajouté')}catch{toast('Impossible d’ajouter le client')}});
document.querySelector('#showAll').addEventListener('click',()=>document.querySelector('[data-view="invoices"]').click());document.querySelector('#invoiceSearch').addEventListener('input',e=>renderInvoices(e.target.value));
document.querySelector('#exportInvoices').addEventListener('click',()=>{const lines=[['Numero','Client','Date','Montant','Statut'],...invoices.map(i=>[i.id,i.client,i.date,Number(i.amount).toFixed(2),i.status])];const csv=lines.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='pilot-factures.csv';a.click();URL.revokeObjectURL(a.href);toast('Export CSV généré')});
document.querySelector('#newQuote').addEventListener('click',()=>toast('Création de devis : prochaine étape du MVP'));

function ensureAuthStyles(){const style=document.createElement('style');style.textContent=`.auth-gate{position:fixed;inset:0;z-index:999;background:#f5f6f8;display:grid;place-items:center;padding:24px}.auth-card{width:min(440px,100%);background:#fff;border:1px solid #e5e7eb;border-radius:20px;padding:34px;box-shadow:0 24px 70px rgba(0,0,0,.1)}.auth-logo{width:42px;height:42px;display:grid;place-items:center;border-radius:12px;background:#15171b;color:#fff;font-weight:900;margin-bottom:22px}.auth-card h2{font-size:28px;letter-spacing:-1px;margin:0 0 7px}.auth-card>p{color:#727784;margin:0 0 25px;font-size:14px}.auth-tabs{display:grid;grid-template-columns:1fr 1fr;background:#f1f2f4;padding:4px;border-radius:10px;margin-bottom:20px}.auth-tab{border:0;background:transparent;padding:9px;border-radius:8px;font-weight:700;cursor:pointer}.auth-tab.active{background:#fff;box-shadow:0 1px 4px rgba(0,0,0,.08)}.auth-field{display:grid;gap:6px;margin:13px 0;font-size:12px;font-weight:700}.auth-field input{padding:12px;border:1px solid #dcdfe4;border-radius:9px}.auth-submit{width:100%;margin-top:10px;border:0;background:#15171b;color:#fff;padding:13px;border-radius:10px;font-weight:800;cursor:pointer}.auth-error{min-height:18px;color:#b42318;font-size:12px;margin-top:10px}.auth-demo{margin-top:18px!important;font-size:11px!important;text-align:center}.auth-hidden{display:none}`;document.head.appendChild(style)}
function showAuthGate(){ensureAuthStyles();const gate=document.createElement('div');gate.className='auth-gate';gate.innerHTML=`<section class="auth-card"><div class="auth-logo">P</div><h2>Bienvenue sur Pilot</h2><p>Connectez-vous à votre espace de gestion.</p><div class="auth-tabs"><button class="auth-tab active" data-auth-tab="login">Connexion</button><button class="auth-tab" data-auth-tab="register">Créer un compte</button></div><form id="loginForm"><label class="auth-field">E-mail<input id="loginEmail" type="email" autocomplete="email" required></label><label class="auth-field">Mot de passe<input id="loginPassword" type="password" autocomplete="current-password" required></label><button class="auth-submit">Se connecter</button></form><form id="registerForm" class="auth-hidden"><label class="auth-field">Nom de l’entreprise<input id="registerOrg" required minlength="2"></label><label class="auth-field">E-mail<input id="registerEmail" type="email" autocomplete="email" required></label><label class="auth-field">Mot de passe<input id="registerPassword" type="password" autocomplete="new-password" minlength="12" required></label><button class="auth-submit">Créer mon espace</button></form><div class="auth-error" id="authError"></div><p class="auth-demo">Votre session est protégée par un cookie HttpOnly. Pilot ne stocke pas votre mot de passe dans le navigateur.</p></section>`;document.body.appendChild(gate);gate.querySelectorAll('.auth-tab').forEach(tab=>tab.onclick=()=>{gate.querySelectorAll('.auth-tab').forEach(x=>x.classList.remove('active'));tab.classList.add('active');gate.querySelector('#loginForm').classList.toggle('auth-hidden',tab.dataset.authTab!=='login');gate.querySelector('#registerForm').classList.toggle('auth-hidden',tab.dataset.authTab!=='register');gate.querySelector('#authError').textContent=''});const finish=async body=>{currentUser=body.data;apiMode=true;await hydrateFromApi();gate.remove();document.querySelector('.demo-pill').textContent='SESSION SÉCURISÉE';renderApp()};gate.querySelector('#loginForm').onsubmit=async e=>{e.preventDefault();try{await finish(await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:gate.querySelector('#loginEmail').value,password:gate.querySelector('#loginPassword').value})}))}catch{gate.querySelector('#authError').textContent='E-mail ou mot de passe incorrect.'}};gate.querySelector('#registerForm').onsubmit=async e=>{e.preventDefault();try{await finish(await api('/api/auth/register',{method:'POST',body:JSON.stringify({organizationName:gate.querySelector('#registerOrg').value,email:gate.querySelector('#registerEmail').value,password:gate.querySelector('#registerPassword').value})}))}catch(err){gate.querySelector('#authError').textContent=err.body?.error==='email_exists'?'Cette adresse e-mail est déjà utilisée.':'Vérifiez les informations. Le mot de passe doit contenir au moins 12 caractères.'}}}

async function boot(){apiMode=await detectApi();if(!apiMode){renderApp();return}try{const me=await api('/api/auth/me');currentUser=me.data;await hydrateFromApi();document.querySelector('.demo-pill').textContent='SESSION SÉCURISÉE';renderApp()}catch(err){if(err.status===401){showAuthGate()}else{apiMode=false;toast('API indisponible — mode démo local');renderApp()}}}
boot();
