let pilotQuotes=[];
function ensureProductUi(){
  if(document.querySelector('[data-view="settings"]'))return;
  const nav=document.querySelector('nav');
  const button=document.createElement('button');button.className='nav';button.dataset.view='settings';button.textContent='Paramètres';nav.appendChild(button);
  const section=document.createElement('section');section.id='settings';section.className='view';section.innerHTML=`<div class="panel"><div class="panel-head"><div><h3>Paramètres entreprise</h3><p>Informations utilisées sur vos documents commerciaux.</p></div></div><form id="companyForm" class="settings-form"><div class="form-grid"><label>Nom de l’entreprise<input id="companyName" required></label><label>E-mail<input id="companyEmail" type="email" required></label></div><label>Adresse<input id="companyAddress" required></label><div class="form-grid"><label>N° TVA / BCE<input id="companyVat" required placeholder="BE0123.456.789"></label><label>IBAN<input id="companyIban" required placeholder="BE00 0000 0000 0000"></label></div><div class="settings-actions"><button class="primary" type="submit">Enregistrer</button><button class="ghost" type="button" id="logoutButton">Se déconnecter</button></div><p class="settings-note">Ces informations apparaissent sur les factures imprimées. Vérifiez-les avant émission.</p></form></div>`;
  document.querySelector('main').appendChild(section);
  const quoteDialog=document.createElement('dialog');quoteDialog.id='quoteDialog';quoteDialog.innerHTML=`<form id="quoteForm"><div class="modal-head"><div><small>NOUVEAU DOCUMENT</small><h3>Créer un devis</h3></div><button type="button" class="close" id="closeQuoteDialog">×</button></div><label>Client<select id="quoteClient" required></select></label><div class="form-grid"><label>Description<input id="quoteDescription" required placeholder="Prestation proposée"></label><label>Montant HTVA (€)<input id="quoteAmountInput" required type="number" min="0.01" step="0.01"></label></div><div class="form-grid"><label>TVA<select id="quoteVat"><option value="21">21 %</option><option value="12">12 %</option><option value="6">6 %</option><option value="0">0 %</option></select></label><label>Valable jusqu’au<input id="quoteValidUntil" type="date"></label></div><button class="primary wide" type="submit">Créer le devis</button></form>`;document.body.appendChild(quoteDialog);
  const style=document.createElement('style');style.textContent=`.settings-form{max-width:760px}.settings-actions{display:flex;gap:10px;align-items:center;margin-top:8px}.settings-note{margin-top:18px!important}.pdf-action,.quote-action{border:0;background:#eef0f3;padding:7px 10px;border-radius:8px;cursor:pointer;font-weight:700;margin-right:5px;font-size:11px}.quote-grid article{position:relative}.quote-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:12px}.quote-meta{color:#777;font-size:12px}.empty{grid-column:1/-1}`;document.head.appendChild(style);
  document.querySelectorAll('.nav').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.nav,.view').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelector('#'+btn.dataset.view).classList.add('active');if(btn.dataset.view==='settings')loadCompanySettings();if(btn.dataset.view==='quotes')loadQuotes();});
  section.querySelector('#companyForm').onsubmit=saveCompanySettings;
  section.querySelector('#logoutButton').onclick=logoutPilot;
  quoteDialog.querySelector('#closeQuoteDialog').onclick=()=>quoteDialog.close();
  quoteDialog.querySelector('#quoteForm').onsubmit=createQuoteFromForm;
  document.querySelector('#newQuote').onclick=openQuoteDialog;
}
async function loadCompanySettings(){if(!apiMode){toast('Les paramètres persistants nécessitent le serveur Pilot');return;}try{const body=await api('/api/v1/organization');const c=body.data;document.querySelector('#companyName').value=c.name||'';document.querySelector('#companyEmail').value=c.email||'';document.querySelector('#companyAddress').value=c.address||'';document.querySelector('#companyVat').value=c.vatNumber||'';document.querySelector('#companyIban').value=c.iban||'';}catch{toast('Impossible de charger les paramètres');}}
async function saveCompanySettings(e){e.preventDefault();try{const payload={name:document.querySelector('#companyName').value.trim(),email:document.querySelector('#companyEmail').value.trim(),address:document.querySelector('#companyAddress').value.trim(),vatNumber:document.querySelector('#companyVat').value.trim(),iban:document.querySelector('#companyIban').value.trim()};const body=await api('/api/v1/organization',{method:'PATCH',body:JSON.stringify(payload)});if(currentUser)currentUser.organization=body.data;renderApp();toast('Paramètres entreprise enregistrés');}catch(err){toast(err.status===400?'Informations entreprise incomplètes':'Impossible d’enregistrer les paramètres');}}
async function logoutPilot(){try{await api('/api/auth/logout',{method:'POST'});}catch{}location.reload();}
function attachPdfButtons(){if(!apiMode)return;document.querySelectorAll('#invoiceRows tr,#allInvoiceRows tr').forEach(tr=>{if(tr.querySelector('.pdf-action'))return;const menu=tr.querySelector('.row-action');if(!menu)return;const pdf=document.createElement('button');pdf.className='pdf-action';pdf.type='button';pdf.textContent='PDF';pdf.onclick=e=>{e.stopPropagation();window.open(`/api/v1/invoices/${encodeURIComponent(menu.dataset.key)}/document`,'_blank','noopener');};menu.parentElement.insertBefore(pdf,menu);});}
const invoiceObserver=new MutationObserver(()=>attachPdfButtons());
function quoteStatusLabel(status){return({draft:'Brouillon',sent:'Envoyé',accepted:'Accepté',rejected:'Refusé',expired:'Expiré',converted:'Converti'})[status]||status;}
function renderQuotes(){const grid=document.querySelector('#quoteGrid');if(!grid)return;const active=pilotQuotes.filter(q=>!['rejected','expired','converted'].includes(q.status));document.querySelector('#quoteCount').textContent=active.length;document.querySelector('#quoteAmount').textContent=euro(active.reduce((s,q)=>s+(q.totals?.gross||0),0));if(!pilotQuotes.length){grid.innerHTML='<div class="empty"><b>Aucun devis</b><p>Créez votre première offre commerciale.</p></div>';return;}grid.innerHTML=pilotQuotes.map(q=>{const client=clients.find(c=>c.id===q.clientId);const canConvert=!q.convertedInvoiceId&&!['rejected','expired'].includes(q.status);return `<article><span>${q.number}</span><b>${client?.name||'Client'}</b><strong>${euro(q.totals?.gross||0)}</strong><small class="status ${q.status==='accepted'||q.status==='converted'?'paid':'pending'}">${quoteStatusLabel(q.status)}</small><div class="quote-meta">Valable jusqu’au ${q.validUntil||'—'}</div><div class="quote-actions">${q.status==='draft'?`<button class="quote-action" data-send="${q.id}">Marquer envoyé</button>`:''}${q.status==='sent'?`<button class="quote-action" data-accept="${q.id}">Accepter</button>`:''}${canConvert?`<button class="quote-action" data-convert="${q.id}">Convertir en facture</button>`:''}</div></article>`;}).join('');grid.querySelectorAll('[data-send]').forEach(b=>b.onclick=()=>changeQuoteStatus(b.dataset.send,'sent'));grid.querySelectorAll('[data-accept]').forEach(b=>b.onclick=()=>changeQuoteStatus(b.dataset.accept,'accepted'));grid.querySelectorAll('[data-convert]').forEach(b=>b.onclick=()=>convertQuote(b.dataset.convert));}
async function loadQuotes(){if(!apiMode){pilotQuotes=[];renderQuotes();return;}try{pilotQuotes=(await api('/api/v1/quotes')).data;renderQuotes();}catch{toast('Impossible de charger les devis');}}
function openQuoteDialog(){if(!apiMode){toast('Les devis réels nécessitent le serveur Pilot');return;}if(!clients.length){toast('Ajoutez d’abord un client');return;}document.querySelector('#quoteClient').innerHTML=clients.map(c=>`<option value="${c.id}">${c.name}</option>`).join('');const d=new Date();d.setDate(d.getDate()+30);document.querySelector('#quoteValidUntil').value=d.toISOString().slice(0,10);document.querySelector('#quoteDialog').showModal();}
async function createQuoteFromForm(e){e.preventDefault();try{const body=await api('/api/v1/quotes',{method:'POST',body:JSON.stringify({clientId:document.querySelector('#quoteClient').value,validUntil:document.querySelector('#quoteValidUntil').value||null,lines:[{description:document.querySelector('#quoteDescription').value.trim(),quantity:1,unitPrice:Number(document.querySelector('#quoteAmountInput').value),vat:Number(document.querySelector('#quoteVat').value),discount:0}]})});pilotQuotes.unshift(body.data);document.querySelector('#quoteDialog').close();e.target.reset();renderQuotes();toast('Devis créé');}catch{toast('Impossible de créer le devis');}}
async function changeQuoteStatus(id,status){try{const body=await api(`/api/v1/quotes/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});const i=pilotQuotes.findIndex(q=>q.id===id);if(i>=0)pilotQuotes[i]=body.data;renderQuotes();toast('Statut du devis mis à jour');}catch{toast('Impossible de modifier le devis');}}
async function convertQuote(id){if(!confirm('Convertir ce devis en facture ? Cette opération ne créera qu’une seule facture.'))return;try{const body=await api(`/api/v1/quotes/${id}/convert`,{method:'POST',body:'{}'});const qi=pilotQuotes.findIndex(q=>q.id===id);if(qi>=0)pilotQuotes[qi]=body.data.quote;await hydrateFromApi();renderInvoices();renderQuotes();toast(`Facture ${body.data.invoice.number} créée`);}catch(err){toast(err.status===409?'Ce devis a déjà été converti':'Impossible de convertir le devis');}}
function startProductEnhancements(){ensureProductUi();document.querySelectorAll('#invoiceRows,#allInvoiceRows').forEach(t=>invoiceObserver.observe(t,{childList:true,subtree:true}));attachPdfButtons();setTimeout(()=>{if(apiMode)loadQuotes();},500);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',startProductEnhancements);else startProductEnhancements();
