function iso(value) { return value?.toISOString?.() || value || null; }
function cents(value) { return Math.round(Number(value || 0) * 100); }
function money(value) { return Number(value || 0) / 100; }
function mapOrganization(row) { return { id: row.id, name: row.name, vatNumber: row.vat_number || '', address: row.address || '', iban: row.iban || '', email: row.email || '', createdAt: iso(row.created_at), updatedAt: iso(row.updated_at) }; }
function mapClient(row) { return { id: row.id, organizationId: row.organization_id, name: row.name, email: row.email || '', vatNumber: row.vat_number || '', address: row.address || '', createdAt: iso(row.created_at), updatedAt: iso(row.updated_at) }; }
function mapInvoiceHeader(row) { return { id: row.id, organizationId: row.organization_id, clientId: row.client_id, number: row.number, status: row.status, issueDate: iso(row.issue_date)?.slice?.(0,10)||row.issue_date, dueDate: iso(row.due_date)?.slice?.(0,10)||row.due_date, totals:{currency:row.currency||'EUR',net:money(row.net_cents),vat:money(row.vat_cents),gross:money(row.gross_cents)}, sourceQuoteId:row.source_quote_id||null, createdAt:iso(row.created_at),updatedAt:iso(row.updated_at)}; }
function mapQuoteHeader(row) { return { id: row.id, organizationId: row.organization_id, clientId: row.client_id, number: row.number, status: row.status, issueDate: iso(row.issue_date)?.slice?.(0,10)||row.issue_date, validUntil: iso(row.valid_until)?.slice?.(0,10)||row.valid_until, totals:{currency:row.currency||'EUR',net:money(row.net_cents),vat:money(row.vat_cents),gross:money(row.gross_cents)}, convertedInvoiceId:row.converted_invoice_id||null, createdAt:iso(row.created_at),updatedAt:iso(row.updated_at)}; }
function mapLine(row) { return { description: row.description, quantity:Number(row.quantity), unitPrice:money(row.unit_price_cents), discount:Number(row.discount_percent), vat:Number(row.vat_rate) }; }
const invoiceSelect=`select id,organization_id,client_id,number,status,issue_date,due_date,currency,net_cents,vat_cents,gross_cents,source_quote_id,created_at,updated_at from invoices`;
const quoteSelect=`select id,organization_id,client_id,number,status,issue_date,valid_until,currency,net_cents,vat_cents,gross_cents,converted_invoice_id,created_at,updated_at from quotes`;

export class PostgresStore {
  constructor(pool){if(!pool||typeof pool.query!=='function')throw new TypeError('A pg-compatible pool is required');this.pool=pool;}
  async getOrganization(id){const{rows}=await this.pool.query('select id,name,vat_number,address,iban,email,created_at,updated_at from organizations where id=$1 limit 1',[id]);return rows[0]?mapOrganization(rows[0]):null;}
  async updateOrganization(id,patch){const c=await this.getOrganization(id);if(!c)return null;const{rows}=await this.pool.query(`update organizations set name=$2,vat_number=$3,address=$4,iban=$5,email=$6,updated_at=now() where id=$1 returning id,name,vat_number,address,iban,email,created_at,updated_at`,[id,patch.name!==undefined?String(patch.name).trim():c.name,patch.vatNumber!==undefined?String(patch.vatNumber).trim():c.vatNumber,patch.address!==undefined?String(patch.address).trim():c.address,patch.iban!==undefined?String(patch.iban).trim():c.iban,patch.email!==undefined?String(patch.email).trim():c.email]);return rows[0]?mapOrganization(rows[0]):null;}
  async findUserByEmail(email){const{rows}=await this.pool.query('select id,email,password_hash,created_at,updated_at from users where lower(email)=lower($1) limit 1',[String(email)]);const r=rows[0];return r?{id:r.id,email:r.email,passwordHash:r.password_hash,createdAt:iso(r.created_at),updatedAt:iso(r.updated_at)}:null;}
  async createUser(input){const{rows}=await this.pool.query('insert into users (email,password_hash) values (lower($1),$2) returning id,email,password_hash,created_at,updated_at',[String(input.email).trim(),input.passwordHash]);const r=rows[0];return{id:r.id,email:r.email,passwordHash:r.password_hash,createdAt:iso(r.created_at),updatedAt:iso(r.updated_at)};}
  async createOrganization(input){const{rows}=await this.pool.query('insert into organizations (name) values ($1) returning id,name,vat_number,address,iban,email,created_at,updated_at',[String(input.name).trim()]);return mapOrganization(rows[0]);}
  async addMembership(organizationId,userId,role='owner'){const{rows}=await this.pool.query('insert into memberships (organization_id,user_id,role) values ($1,$2,$3) returning organization_id,user_id,role',[organizationId,userId,role]);return{organizationId:rows[0].organization_id,userId:rows[0].user_id,role:rows[0].role};}
  async listMemberships(userId){const{rows}=await this.pool.query(`select m.organization_id,m.user_id,m.role,o.id,o.name,o.vat_number,o.address,o.iban,o.email,o.created_at,o.updated_at from memberships m join organizations o on o.id=m.organization_id where m.user_id=$1 order by o.created_at asc`,[userId]);return rows.map(r=>({organizationId:r.organization_id,userId:r.user_id,role:r.role,organization:mapOrganization(r)}));}
  async createSession(input){const{rows}=await this.pool.query(`insert into sessions (token_hash,user_id,organization_id,expires_at) values ($1,$2,$3,$4) returning id,token_hash,user_id,organization_id,expires_at,created_at`,[input.tokenHash,input.userId,input.organizationId,input.expiresAt]);const r=rows[0];return{id:r.id,tokenHash:r.token_hash,userId:r.user_id,organizationId:r.organization_id,expiresAt:iso(r.expires_at),createdAt:iso(r.created_at)};}
  async getSession(tokenHash){const{rows}=await this.pool.query(`select s.id,s.token_hash,s.user_id,s.organization_id,s.expires_at,s.created_at,u.email,m.role from sessions s join users u on u.id=s.user_id join memberships m on m.user_id=s.user_id and m.organization_id=s.organization_id where s.token_hash=$1 and s.expires_at>now() limit 1`,[tokenHash]);const r=rows[0];if(!r)return null;await this.pool.query('update sessions set last_seen_at=now() where id=$1',[r.id]);return{id:r.id,tokenHash:r.token_hash,userId:r.user_id,organizationId:r.organization_id,expiresAt:iso(r.expires_at),createdAt:iso(r.created_at),role:r.role,user:{id:r.user_id,email:r.email}};}
  async deleteSession(tokenHash){const r=await this.pool.query('delete from sessions where token_hash=$1',[tokenHash]);return r.rowCount>0;}
  async listClients(organizationId){const{rows}=await this.pool.query(`select id,organization_id,name,email,vat_number,address,created_at,updated_at from clients where organization_id=$1 order by created_at desc`,[organizationId]);return rows.map(mapClient);}
  async getClient(organizationId,id){const{rows}=await this.pool.query(`select id,organization_id,name,email,vat_number,address,created_at,updated_at from clients where organization_id=$1 and id=$2 limit 1`,[organizationId,id]);return rows[0]?mapClient(rows[0]):null;}
  async createClient(organizationId,input){const{rows}=await this.pool.query(`insert into clients (organization_id,name,email,vat_number,address) values ($1,$2,$3,$4,$5) returning id,organization_id,name,email,vat_number,address,created_at,updated_at`,[organizationId,String(input.name||'').trim(),String(input.email||'').trim(),String(input.vatNumber||'').trim(),String(input.address||'').trim()]);return mapClient(rows[0]);}
  async updateClient(organizationId,id,patch){const c=await this.getClient(organizationId,id);if(!c)return null;const{rows}=await this.pool.query(`update clients set name=$3,email=$4,vat_number=$5,address=$6,updated_at=now() where organization_id=$1 and id=$2 returning id,organization_id,name,email,vat_number,address,created_at,updated_at`,[organizationId,id,patch.name!==undefined?String(patch.name).trim():c.name,patch.email!==undefined?String(patch.email).trim():c.email,patch.vatNumber!==undefined?String(patch.vatNumber).trim():c.vatNumber,patch.address!==undefined?String(patch.address).trim():c.address]);return rows[0]?mapClient(rows[0]):null;}
  async deleteClient(organizationId,id){const linked=await this.pool.query(`select 1 from (select client_id from invoices where organization_id=$1 union all select client_id from quotes where organization_id=$1) d where client_id=$2 limit 1`,[organizationId,id]);if(linked.rowCount)return{deleted:false,reason:'client_has_documents'};const r=await this.pool.query('delete from clients where organization_id=$1 and id=$2',[organizationId,id]);return{deleted:r.rowCount>0};}
  async _withLines(headers,table,fk,mapper){if(!headers.length)return[];const ids=headers.map(r=>r.id);const{rows}=await this.pool.query(`select ${fk},position,description,quantity,unit_price_cents,discount_percent,vat_rate from ${table} where ${fk}=any($1::uuid[]) order by ${fk},position`,[ids]);const grouped=new Map();for(const r of rows){if(!grouped.has(r[fk]))grouped.set(r[fk],[]);grouped.get(r[fk]).push(mapLine(r));}return headers.map(r=>({...mapper(r),lines:grouped.get(r.id)||[]}));}
  async listInvoices(organizationId){const{rows}=await this.pool.query(`${invoiceSelect} where organization_id=$1 order by created_at desc`,[organizationId]);return this._withLines(rows,'invoice_lines','invoice_id',mapInvoiceHeader);}
  async getInvoice(organizationId,id){const{rows}=await this.pool.query(`${invoiceSelect} where organization_id=$1 and id=$2 limit 1`,[organizationId,id]);const x=await this._withLines(rows,'invoice_lines','invoice_id',mapInvoiceHeader);return x[0]||null;}
  async createInvoice(organizationId,input){const client=await this.pool.connect();try{await client.query('begin');const t=input.totals||{};const{rows}=await client.query(`insert into invoices (organization_id,client_id,number,status,issue_date,due_date,currency,net_cents,vat_cents,gross_cents,source_quote_id) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) returning id,organization_id,client_id,number,status,issue_date,due_date,currency,net_cents,vat_cents,gross_cents,source_quote_id,created_at,updated_at`,[organizationId,input.clientId,input.number,input.status||'draft',input.issueDate||new Date().toISOString().slice(0,10),input.dueDate||null,t.currency||'EUR',cents(t.net),cents(t.vat??t.vatAmount),cents(t.gross),input.sourceQuoteId||null]);const inv=rows[0];for(const[index,line]of(input.lines||[]).entries())await client.query(`insert into invoice_lines (invoice_id,position,description,quantity,unit_price_cents,discount_percent,vat_rate) values ($1,$2,$3,$4,$5,$6,$7)`,[inv.id,index+1,line.description,Number(line.quantity),cents(line.unitPrice),Number(line.discount||0),Number(line.vat)]);await client.query('commit');return{...mapInvoiceHeader(inv),lines:structuredClone(input.lines||[])};}catch(e){await client.query('rollback');throw e;}finally{client.release();}}
  async updateInvoiceStatus(organizationId,id,status){const{rows}=await this.pool.query(`update invoices set status=$3,updated_at=now() where organization_id=$1 and id=$2 returning id,organization_id,client_id,number,status,issue_date,due_date,currency,net_cents,vat_cents,gross_cents,source_quote_id,created_at,updated_at`,[organizationId,id,status]);if(!rows[0])return null;const x=await this._withLines(rows,'invoice_lines','invoice_id',mapInvoiceHeader);return x[0]||null;}
  async listQuotes(organizationId){const{rows}=await this.pool.query(`${quoteSelect} where organization_id=$1 order by created_at desc`,[organizationId]);return this._withLines(rows,'quote_lines','quote_id',mapQuoteHeader);}
  async getQuote(organizationId,id){const{rows}=await this.pool.query(`${quoteSelect} where organization_id=$1 and id=$2 limit 1`,[organizationId,id]);const x=await this._withLines(rows,'quote_lines','quote_id',mapQuoteHeader);return x[0]||null;}
  async createQuote(organizationId,input){const client=await this.pool.connect();try{await client.query('begin');const t=input.totals||{};const{rows}=await client.query(`insert into quotes (organization_id,client_id,number,status,issue_date,valid_until,currency,net_cents,vat_cents,gross_cents) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning id,organization_id,client_id,number,status,issue_date,valid_until,currency,net_cents,vat_cents,gross_cents,converted_invoice_id,created_at,updated_at`,[organizationId,input.clientId,input.number,input.status||'draft',input.issueDate||new Date().toISOString().slice(0,10),input.validUntil||null,t.currency||'EUR',cents(t.net),cents(t.vat??t.vatAmount),cents(t.gross)]);const q=rows[0];for(const[index,line]of(input.lines||[]).entries())await client.query(`insert into quote_lines (quote_id,position,description,quantity,unit_price_cents,discount_percent,vat_rate) values ($1,$2,$3,$4,$5,$6,$7)`,[q.id,index+1,line.description,Number(line.quantity),cents(line.unitPrice),Number(line.discount||0),Number(line.vat)]);await client.query('commit');return{...mapQuoteHeader(q),lines:structuredClone(input.lines||[])};}catch(e){await client.query('rollback');throw e;}finally{client.release();}}
  async updateQuoteStatus(organizationId,id,status){const{rows}=await this.pool.query(`update quotes set status=$3,updated_at=now() where organization_id=$1 and id=$2 returning id,organization_id,client_id,number,status,issue_date,valid_until,currency,net_cents,vat_cents,gross_cents,converted_invoice_id,created_at,updated_at`,[organizationId,id,status]);if(!rows[0])return null;const x=await this._withLines(rows,'quote_lines','quote_id',mapQuoteHeader);return x[0]||null;}
  async markQuoteConverted(organizationId,id,invoiceId){const{rows}=await this.pool.query(`update quotes set status='converted',converted_invoice_id=$3,updated_at=now() where organization_id=$1 and id=$2 and converted_invoice_id is null returning id,organization_id,client_id,number,status,issue_date,valid_until,currency,net_cents,vat_cents,gross_cents,converted_invoice_id,created_at,updated_at`,[organizationId,id,invoiceId]);if(rows[0])return{alreadyConverted:false,quote:mapQuoteHeader(rows[0])};const current=await this.getQuote(organizationId,id);return current?{alreadyConverted:true,quote:current}:null;}
}
