extends RefCounted
class_name BrusselsGenericWindowSurfaceMaterial

## Reusable texture-free presentation material for the existing generic-window
## MultiMesh generated by osm_city_builder.gd. The parent buildings use OSM
## footprint/placement data, but the opening rhythm itself is an authored
## presentation heuristic. Nothing here claims observed fenestration, glass
## type, tint, reflectance, roughness, age, measured colour or photometry.

const MATERIAL_FAMILY := "brussels_generic_window_surface_v1"
const SOURCE_LABEL := "OpenStreetMap contributors via Overpass API for parent building footprint/placement only; generic window opening rhythm and surface recipe are authored presentation; ODbL-1.0"

static func _shader() -> Shader:
    var shader := Shader.new()
    shader.code = """
shader_type spatial;
render_mode diffuse_burley, specular_schlick_ggx;

uniform vec4 base_color : source_color = vec4(0.045, 0.075, 0.095, 1.0);
uniform float base_roughness : hint_range(0.0, 1.0) = 0.24;
uniform float base_metallic : hint_range(0.0, 1.0) = 0.16;

varying vec3 world_pos;

float hash21(vec2 p) {
    p = fract(p * vec2(123.34, 456.21));
    p += dot(p, p + 45.32);
    return fract(p.x * p.y);
}

void vertex() {
    world_pos = (MODEL_MATRIX * vec4(VERTEX, 1.0)).xyz;
}

void fragment() {
    vec2 cell = floor(world_pos.xz * 0.22 + vec2(17.0, 43.0));
    float panel = hash21(cell);
    float broad = sin(world_pos.y * 0.58 + world_pos.x * 0.031 + world_pos.z * 0.027);
    float tonal = (panel - 0.5) * 0.18 + broad * 0.035;
    vec3 authored_tint = vec3(0.90, 0.98, 1.06);
    ALBEDO = clamp(base_color.rgb * authored_tint * (1.0 + tonal), vec3(0.0), vec3(1.0));
    ROUGHNESS = clamp(base_roughness + (0.5 - panel) * 0.08, 0.14, 0.42);
    METALLIC = clamp(base_metallic, 0.0, 0.22);
    SPECULAR = 0.52;
}
"""
    return shader

static func create_material(base_color: Color, roughness: float, metallic: float) -> ShaderMaterial:
    var material := ShaderMaterial.new()
    material.shader = _shader()
    material.set_shader_parameter("base_color", base_color)
    material.set_shader_parameter("base_roughness", roughness)
    material.set_shader_parameter("base_metallic", metallic)
    material.set_meta("material_family", MATERIAL_FAMILY)
    material.set_meta("source_label", SOURCE_LABEL)
    material.set_meta("license", "ODbL-1.0")
    material.set_meta("procedural_only", true)
    material.set_meta("opening_geometry_claimed", false)
    material.set_meta("window_count_claimed_from_source", false)
    material.set_meta("glass_identity_claimed", false)
    material.set_meta("glass_tint_claimed", false)
    material.set_meta("reflectance_measured", false)
    material.set_meta("roughness_measured", false)
    material.set_meta("exact_rgb_is_photometric_measurement", false)
    material.set_meta("geometry_changed", false)
    material.set_meta("visual_recipe_provenance", "authored_presentation_not_source_measurement")
    return material
