extends Node

## Adds low-cost architectural depth to the already-authorized OSM corridor
## facade placements. This never creates or moves building volumes: it derives
## trims and material variants exclusively from existing visible window/shop
## transforms generated by osm_city_builder.gd.

const DETAILS_PATH := NodePath("../BrusselsOSM/GeneratedFacadeDetails")
const WINDOW_NODE := "CorridorFacadeWindows"
const SHOP_NODE := "CorridorShopfronts"
const WINDOW_TRIM_PALETTE: Array[Color] = [
    Color(0.57, 0.535, 0.46, 1.0),
    Color(0.62, 0.59, 0.52, 1.0),
    Color(0.50, 0.48, 0.43, 1.0),
    Color(0.66, 0.62, 0.55, 1.0),
    Color(0.46, 0.44, 0.40, 1.0),
]
const WINDOW_TRIM_PERMUTATION: Array[int] = [0, 3, 1, 4, 2]
const WINDOW_TRIM_ROUGHNESS: Array[float] = [0.93, 0.90, 0.96, 0.88, 0.94]
const SHOP_CANOPY_PALETTE: Array[Color] = [
    Color(0.23, 0.095, 0.085, 1.0),
    Color(0.075, 0.19, 0.17, 1.0),
    Color(0.075, 0.13, 0.225, 1.0),
    Color(0.245, 0.16, 0.09, 1.0),
    Color(0.145, 0.15, 0.155, 1.0),
]
const SHOP_CANOPY_PERMUTATION: Array[int] = [0, 3, 1, 4, 2]
const SHOP_GLASS_PALETTE: Array[Color] = [
    Color(0.055, 0.105, 0.135, 1.0),
    Color(0.075, 0.135, 0.155, 1.0),
    Color(0.045, 0.085, 0.115, 1.0),
    Color(0.095, 0.145, 0.165, 1.0),
]
const SHOP_GLASS_PERMUTATION: Array[int] = [0, 2, 1, 3]
const SHOP_GLASS_ROUGHNESS: Array[float] = [0.18, 0.23, 0.29, 0.32]
const SHOP_GLASS_METALLIC: Array[float] = [0.12, 0.16, 0.20, 0.24]
const WINDOW_GLASS_PALETTE: Array[Color] = [
    Color(0.050, 0.090, 0.115, 1.0),
    Color(0.070, 0.115, 0.140, 1.0),
    Color(0.090, 0.130, 0.150, 1.0),
    Color(0.060, 0.100, 0.130, 1.0),
    Color(0.105, 0.145, 0.165, 1.0),
]
const WINDOW_GLASS_PERMUTATION: Array[int] = [0, 3, 1, 4, 2]
const WINDOW_GLASS_ROUGHNESS: Array[float] = [0.20, 0.24, 0.29, 0.33, 0.36]
const WINDOW_GLASS_METALLIC: Array[float] = [0.08, 0.11, 0.14, 0.17, 0.20]

var articulation_ready := false
var lintel_count := 0
var sill_count := 0
var jamb_count := 0
var trim_material_group_count := 0
var canopy_count := 0
var canopy_material_group_count := 0
var glass_count := 0
var glass_material_group_count := 0
var window_glass_count := 0
var window_glass_material_group_count := 0

func _ready() -> void:
    call_deferred("_build")

func _material(color: Color, roughness: float = 0.85, metallic: float = 0.0) -> StandardMaterial3D:
    var material := StandardMaterial3D.new()
    material.albedo_color = color
    material.roughness = roughness
    material.metallic = metallic
    return material

func _unit_multimesh(name: String, transforms: Array[Transform3D], material: Material) -> MultiMeshInstance3D:
    var mesh := BoxMesh.new()
    mesh.size = Vector3.ONE
    mesh.material = material
    var multimesh := MultiMesh.new()
    multimesh.transform_format = MultiMesh.TRANSFORM_3D
    multimesh.mesh = mesh
    multimesh.instance_count = transforms.size()
    for index: int in range(transforms.size()):
        multimesh.set_instance_transform(index, transforms[index])
    var instance := MultiMeshInstance3D.new()
    instance.name = name
    instance.multimesh = multimesh
    return instance

func _clean_basis(transform: Transform3D) -> Basis:
    var rotation := transform.basis.orthonormalized()
    if rotation.determinant() < 0.0:
        rotation = Basis(rotation.x * -1.0, rotation.y, rotation.z)
    return rotation

func _window_articulation(window_transform: Transform3D, lintels: Array[Transform3D], sills: Array[Transform3D], jambs: Array[Transform3D]) -> void:
    var scale := window_transform.basis.get_scale().abs()
    var rotation := _clean_basis(window_transform)
    var origin := window_transform.origin
    var horizontal := rotation.x.normalized()
    var trim_depth := maxf(0.16, scale.z + 0.06)
    var cap_width := scale.x + 0.24
    var cap_offset := scale.y * 0.5 + 0.10
    var side_offset := scale.x * 0.5 + 0.09

    lintels.append(Transform3D(rotation.scaled(Vector3(cap_width, 0.16, trim_depth)), origin + Vector3.UP * cap_offset))
    sills.append(Transform3D(rotation.scaled(Vector3(cap_width, 0.12, trim_depth + 0.03)), origin - Vector3.UP * cap_offset))
    var jamb_scale := Vector3(0.14, scale.y + 0.18, trim_depth)
    jambs.append(Transform3D(rotation.scaled(jamb_scale), origin + horizontal * side_offset))
    jambs.append(Transform3D(rotation.scaled(jamb_scale), origin - horizontal * side_offset))

func _window_trim_index(instance_index: int) -> int:
    # A complete five-window block sees every stone family once. The block
    # rotation prevents a single repeating global phase while remaining stable.
    var lane: int = instance_index % WINDOW_TRIM_PERMUTATION.size()
    var block: int = instance_index / WINDOW_TRIM_PERMUTATION.size()
    var rotation: int = (block * 4 + block * block * 2) % WINDOW_TRIM_PERMUTATION.size()
    return (WINDOW_TRIM_PERMUTATION[lane] + rotation) % WINDOW_TRIM_PALETTE.size()

func _build_window_trim(details: Node3D, lintels: Array[Transform3D], sills: Array[Transform3D], jambs: Array[Transform3D]) -> void:
    for palette_index: int in range(WINDOW_TRIM_PALETTE.size()):
        var lintel_group: Array[Transform3D] = []
        var sill_group: Array[Transform3D] = []
        var jamb_group: Array[Transform3D] = []
        for index: int in range(lintels.size()):
            if _window_trim_index(index) != palette_index:
                continue
            lintel_group.append(lintels[index])
            sill_group.append(sills[index])
            jamb_group.append(jambs[index * 2])
            jamb_group.append(jambs[index * 2 + 1])
        if lintel_group.is_empty():
            continue
        var suffix := "" if palette_index == 0 else "_%d" % palette_index
        var trim_material := _material(WINDOW_TRIM_PALETTE[palette_index], WINDOW_TRIM_ROUGHNESS[palette_index])
        details.add_child(_unit_multimesh("CorridorFacadeLintels%s" % suffix, lintel_group, trim_material))
        details.add_child(_unit_multimesh("CorridorFacadeSills%s" % suffix, sill_group, trim_material))
        details.add_child(_unit_multimesh("CorridorFacadeJambs%s" % suffix, jamb_group, trim_material))
        lintel_count += lintel_group.size()
        sill_count += sill_group.size()
        jamb_count += jamb_group.size()
        trim_material_group_count += 1

func _shop_canopy(shop_transform: Transform3D) -> Transform3D:
    var scale := shop_transform.basis.get_scale().abs()
    var rotation := _clean_basis(shop_transform)
    var outward := rotation.z.normalized()
    var origin := shop_transform.origin + Vector3.UP * (scale.y * 0.5 + 0.14) + outward * 0.28
    return Transform3D(rotation.scaled(Vector3(scale.x + 0.34, 0.12, 0.72)), origin)

func _shop_palette_index(_origin: Vector3, instance_index: int) -> int:
    var lane: int = instance_index % SHOP_CANOPY_PERMUTATION.size()
    var block: int = instance_index / SHOP_CANOPY_PERMUTATION.size()
    var rotation: int = (block * 3 + block * block * 2) % SHOP_CANOPY_PERMUTATION.size()
    return (SHOP_CANOPY_PERMUTATION[lane] + rotation) % SHOP_CANOPY_PALETTE.size()

func _shop_glass_index(instance_index: int) -> int:
    var lane: int = instance_index % SHOP_GLASS_PERMUTATION.size()
    var block: int = instance_index / SHOP_GLASS_PERMUTATION.size()
    var rotation: int = (block * 3 + block * block) % SHOP_GLASS_PERMUTATION.size()
    return (SHOP_GLASS_PERMUTATION[lane] + rotation) % SHOP_GLASS_PALETTE.size()

func _window_glass_index(instance_index: int) -> int:
    var lane: int = instance_index % WINDOW_GLASS_PERMUTATION.size()
    var block: int = instance_index / WINDOW_GLASS_PERMUTATION.size()
    var rotation: int = (block * 2 + block * block * 3) % WINDOW_GLASS_PERMUTATION.size()
    return (WINDOW_GLASS_PERMUTATION[lane] + rotation) % WINDOW_GLASS_PALETTE.size()

func _build_shop_canopies(details: Node3D, shop_node: MultiMeshInstance3D) -> void:
    var shop_multimesh := shop_node.multimesh
    if shop_multimesh == null:
        return
    for palette_index: int in range(SHOP_CANOPY_PALETTE.size()):
        var transforms: Array[Transform3D] = []
        for index: int in range(shop_multimesh.instance_count):
            var shop_transform: Transform3D = shop_multimesh.get_instance_transform(index)
            if _shop_palette_index(shop_transform.origin, index) != palette_index:
                continue
            transforms.append(_shop_canopy(shop_transform))
        if transforms.is_empty():
            continue
        var node_name := "CorridorShopCanopies" if palette_index == 0 else "CorridorShopCanopies_%d" % palette_index
        var canopy_material := _material(SHOP_CANOPY_PALETTE[palette_index], 0.54, 0.12)
        details.add_child(_unit_multimesh(node_name, transforms, canopy_material))
        canopy_count += transforms.size()
        canopy_material_group_count += 1

func _build_shopfront_glass(details: Node3D, shop_node: MultiMeshInstance3D) -> void:
    var shop_multimesh := shop_node.multimesh
    if shop_multimesh == null:
        return
    for palette_index: int in range(SHOP_GLASS_PALETTE.size()):
        var transforms: Array[Transform3D] = []
        for index: int in range(shop_multimesh.instance_count):
            if _shop_glass_index(index) != palette_index:
                continue
            transforms.append(shop_multimesh.get_instance_transform(index))
        if transforms.is_empty():
            continue
        var node_name := "CorridorShopfrontGlass" if palette_index == 0 else "CorridorShopfrontGlass_%d" % palette_index
        var glass_material := _material(SHOP_GLASS_PALETTE[palette_index], SHOP_GLASS_ROUGHNESS[palette_index], SHOP_GLASS_METALLIC[palette_index])
        details.add_child(_unit_multimesh(node_name, transforms, glass_material))
        glass_count += transforms.size()
        glass_material_group_count += 1
    shop_node.visible = false

func _build_window_glass(details: Node3D, windows_node: MultiMeshInstance3D) -> void:
    var windows_multimesh := windows_node.multimesh
    if windows_multimesh == null:
        return
    for palette_index: int in range(WINDOW_GLASS_PALETTE.size()):
        var transforms: Array[Transform3D] = []
        for index: int in range(windows_multimesh.instance_count):
            if _window_glass_index(index) != palette_index:
                continue
            transforms.append(windows_multimesh.get_instance_transform(index))
        if transforms.is_empty():
            continue
        var node_name := "CorridorWindowGlass" if palette_index == 0 else "CorridorWindowGlass_%d" % palette_index
        var window_material := _material(WINDOW_GLASS_PALETTE[palette_index], WINDOW_GLASS_ROUGHNESS[palette_index], WINDOW_GLASS_METALLIC[palette_index])
        details.add_child(_unit_multimesh(node_name, transforms, window_material))
        window_glass_count += transforms.size()
        window_glass_material_group_count += 1
    windows_node.visible = false

func _build() -> void:
    var details := get_node_or_null(DETAILS_PATH) as Node3D
    if details == null:
        push_error("CorridorFacadeDepthRuntime: GeneratedFacadeDetails missing")
        return
    var windows_node := details.get_node_or_null(WINDOW_NODE) as MultiMeshInstance3D
    if windows_node == null or windows_node.multimesh == null:
        push_error("CorridorFacadeDepthRuntime: baseline window MultiMesh missing")
        return

    var lintels: Array[Transform3D] = []
    var sills: Array[Transform3D] = []
    var jambs: Array[Transform3D] = []
    var windows := windows_node.multimesh
    for index: int in range(windows.instance_count):
        _window_articulation(windows.get_instance_transform(index), lintels, sills, jambs)

    # Geometry is derived once from the canonical window transforms, then only
    # partitioned by material family. No trim transform is regenerated or moved.
    _build_window_trim(details, lintels, sills, jambs)
    _build_window_glass(details, windows_node)

    var shop_node := details.get_node_or_null(SHOP_NODE) as MultiMeshInstance3D
    if shop_node != null:
        _build_shop_canopies(details, shop_node)
        _build_shopfront_glass(details, shop_node)

    articulation_ready = lintel_count == windows.instance_count and sill_count == windows.instance_count and jamb_count == windows.instance_count * 2
    if articulation_ready:
        print("CORRIDOR_FACADE_DEPTH_READY: windows=%d lintels=%d sills=%d jambs=%d trim_groups=%d window_glass=%d window_groups=%d canopies=%d canopy_groups=%d glass=%d glass_groups=%d" % [windows.instance_count, lintel_count, sill_count, jamb_count, trim_material_group_count, window_glass_count, window_glass_material_group_count, canopy_count, canopy_material_group_count, glass_count, glass_material_group_count])
    else:
        push_error("CorridorFacadeDepthRuntime: articulation count mismatch")
