extends Node

## Adds low-cost architectural depth to the already-authorized OSM corridor
## facade placements. This never creates or moves building volumes: it derives
## lintels, sills, jambs and shop canopies exclusively from existing visible
## window/shop transforms generated by osm_city_builder.gd.

const DETAILS_PATH := NodePath("../BrusselsOSM/GeneratedFacadeDetails")
const WINDOW_NODE := "CorridorFacadeWindows"
const SHOP_NODE := "CorridorShopfronts"
const SHOP_CANOPY_PALETTE: Array[Color] = [
    Color(0.23, 0.095, 0.085, 1.0),
    Color(0.075, 0.19, 0.17, 1.0),
    Color(0.075, 0.13, 0.225, 1.0),
    Color(0.245, 0.16, 0.09, 1.0),
    Color(0.145, 0.15, 0.155, 1.0),
]

var articulation_ready := false
var lintel_count := 0
var sill_count := 0
var jamb_count := 0
var canopy_count := 0

func _ready() -> void:
    call_deferred("_build")

func _material(color: Color, roughness: float, metallic: float = 0.0) -> StandardMaterial3D:
    var material := StandardMaterial3D.new()
    material.albedo_color = color
    material.roughness = roughness
    material.metallic = metallic
    return material

func _unit_multimesh(name: String, transforms: Array[Transform3D], material: Material) -> MultiMeshInstance3D:
    var mesh := BoxMesh.new()
    mesh.size = Vector3.ONE
    mesh.material = material
    var multimesh := MultiMesh.new()
    multimesh.transform_format = MultiMesh.TRANSFORM_3D
    multimesh.mesh = mesh
    multimesh.instance_count = transforms.size()
    for index: int in range(transforms.size()):
        multimesh.set_instance_transform(index, transforms[index])
    var instance := MultiMeshInstance3D.new()
    instance.name = name
    instance.multimesh = multimesh
    return instance

func _colored_unit_multimesh(name: String, transforms: Array[Transform3D], colors: Array[Color], material: StandardMaterial3D) -> MultiMeshInstance3D:
    var mesh := BoxMesh.new()
    mesh.size = Vector3.ONE
    material.vertex_color_use_as_albedo = true
    mesh.material = material
    var multimesh := MultiMesh.new()
    multimesh.transform_format = MultiMesh.TRANSFORM_3D
    multimesh.use_colors = true
    multimesh.mesh = mesh
    multimesh.instance_count = transforms.size()
    for index: int in range(transforms.size()):
        multimesh.set_instance_transform(index, transforms[index])
        multimesh.set_instance_color(index, colors[index])
    var instance := MultiMeshInstance3D.new()
    instance.name = name
    instance.multimesh = multimesh
    return instance

func _clean_basis(transform: Transform3D) -> Basis:
    var rotation := transform.basis.orthonormalized()
    if rotation.determinant() < 0.0:
        rotation = Basis(rotation.x * -1.0, rotation.y, rotation.z)
    return rotation

func _window_articulation(window_transform: Transform3D, lintels: Array[Transform3D], sills: Array[Transform3D], jambs: Array[Transform3D]) -> void:
    var scale := window_transform.basis.get_scale().abs()
    var rotation := _clean_basis(window_transform)
    var origin := window_transform.origin
    var horizontal := rotation.x.normalized()
    var trim_depth := maxf(0.16, scale.z + 0.06)
    var cap_width := scale.x + 0.24
    var cap_offset := scale.y * 0.5 + 0.10
    var side_offset := scale.x * 0.5 + 0.09

    lintels.append(Transform3D(rotation.scaled(Vector3(cap_width, 0.16, trim_depth)), origin + Vector3.UP * cap_offset))
    sills.append(Transform3D(rotation.scaled(Vector3(cap_width, 0.12, trim_depth + 0.03)), origin - Vector3.UP * cap_offset))
    var jamb_scale := Vector3(0.14, scale.y + 0.18, trim_depth)
    jambs.append(Transform3D(rotation.scaled(jamb_scale), origin + horizontal * side_offset))
    jambs.append(Transform3D(rotation.scaled(jamb_scale), origin - horizontal * side_offset))

func _shop_canopy(shop_transform: Transform3D) -> Transform3D:
    var scale := shop_transform.basis.get_scale().abs()
    var rotation := _clean_basis(shop_transform)
    var outward := rotation.z.normalized()
    var origin := shop_transform.origin + Vector3.UP * (scale.y * 0.5 + 0.14) + outward * 0.28
    return Transform3D(rotation.scaled(Vector3(scale.x + 0.34, 0.12, 0.72)), origin)

func _shop_palette_index(origin: Vector3) -> int:
    # Quantized world position keeps the choice stable across runs and independent
    # of frame order, while breaking the obvious adjacent A/B/C sequence look.
    var x_key: int = int(round(origin.x * 2.0))
    var z_key: int = int(round(origin.z * 2.0))
    var mixed: int = int(abs(x_key * 73856093 + z_key * 19349663 + x_key * z_key * 83492791))
    return mixed % SHOP_CANOPY_PALETTE.size()

func _shop_canopy_color(shop_transform: Transform3D) -> Color:
    return SHOP_CANOPY_PALETTE[_shop_palette_index(shop_transform.origin)]

func _build() -> void:
    var details := get_node_or_null(DETAILS_PATH) as Node3D
    if details == null:
        push_error("CorridorFacadeDepthRuntime: GeneratedFacadeDetails missing")
        return
    var windows_node := details.get_node_or_null(WINDOW_NODE) as MultiMeshInstance3D
    if windows_node == null or windows_node.multimesh == null:
        push_error("CorridorFacadeDepthRuntime: baseline window MultiMesh missing")
        return

    var lintels: Array[Transform3D] = []
    var sills: Array[Transform3D] = []
    var jambs: Array[Transform3D] = []
    var windows := windows_node.multimesh
    for index: int in range(windows.instance_count):
        _window_articulation(windows.get_instance_transform(index), lintels, sills, jambs)

    var trim_material := _material(Color(0.57, 0.535, 0.46, 1.0), 0.93)
    details.add_child(_unit_multimesh("CorridorFacadeLintels", lintels, trim_material))
    details.add_child(_unit_multimesh("CorridorFacadeSills", sills, trim_material))
    details.add_child(_unit_multimesh("CorridorFacadeJambs", jambs, trim_material))
    lintel_count = lintels.size()
    sill_count = sills.size()
    jamb_count = jambs.size()

    var shop_node := details.get_node_or_null(SHOP_NODE) as MultiMeshInstance3D
    if shop_node != null and shop_node.multimesh != null:
        var canopies: Array[Transform3D] = []
        var canopy_colors: Array[Color] = []
        for index: int in range(shop_node.multimesh.instance_count):
            var shop_transform := shop_node.multimesh.get_instance_transform(index)
            canopies.append(_shop_canopy(shop_transform))
            canopy_colors.append(_shop_canopy_color(shop_transform))
        if not canopies.is_empty():
            var canopy_material := _material(Color.WHITE, 0.54, 0.12)
            details.add_child(_colored_unit_multimesh("CorridorShopCanopies", canopies, canopy_colors, canopy_material))
            canopy_count = canopies.size()

    articulation_ready = lintel_count == windows.instance_count and sill_count == windows.instance_count and jamb_count == windows.instance_count * 2
    if articulation_ready:
        print("CORRIDOR_FACADE_DEPTH_READY: windows=%d lintels=%d sills=%d jambs=%d canopies=%d" % [windows.instance_count, lintel_count, sill_count, jamb_count, canopy_count])
    else:
        push_error("CorridorFacadeDepthRuntime: articulation count mismatch")
